#!/usr/bin/python
# 
# 
# 
# 
# Kim Brugger (05 Nov 2015), contact: kim@brugger.dk

import sys
import pprint
pp = pprint.PrettyPrinter(indent=4)

dna = "AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGC";

dna = "ATGGGCCGGGCCCATTAGGTAATGGGTTGAGAAACTGAACCCCGTAATAGACTAGAAGTCTACCCGATCTACGGTCCCTAAGAAGGAGGCATCCGCAGTTCTCAATTGCCCACTCCTCATTCTCTTCGGATACGTCTGTATACCGGTTCATGAACTATCATGGACCGACGATCTATTCCACATTGAGCAGGTCGCCCCTGGTCGGCATCGAAGTCTTAGCTTCCATACGACGTTATGAAAACTGGTAGATACACAACTCTTTGTGTACGGAGTGTACTATCATGAGGTGCTCTGCCATTCAGACTCTCTGCCCTACTGCCAGGGATTTCACGTAGTGATGGACATGCTTTTTGCCCAGACATTGTAATTTGATCTAAACTTTGTCCGCCTGCGTTTCTGAGCGATGCGCTACCGCCGGGGTTGACCGGCCTAAACCACGCTCTAGCTTGCAAGCTCGGATTCGACGGCTAGGCTAAGTGAGGCTTCTTCCCCTAGATGGTCGTAACGTTTGCCCGCCCTGCTCGCGAGCTCTGCAATTTCGTATGGATATCGCCTTGCGGGGCAACTTTTCACCTACTCAATCATGTTTATCGCTGCCCCTAAGGGACGTTCCCCTGAATACCCCGAAACACAGACTCCTCTGCGTATACCGGCTGGTTATTGTACGAAGACCCCAGTGGGAGCAGGATCTTCTAGCCATAACATACTTGGAGAATAGCCAGAGTCTGTATCATCTAAGTAAACACGCCCTGTTCATAACTTTGCGAAGACTCGTGTTTTGATTTGCGATGGAACTCTATAAACACGTTCCGCAACACTT"

As = 0
Cs = 0
Gs = 0
Ts = 0


for i in range(0, len(dna)):

    if ( dna[ i ] == 'A' ):
        As += 1;
    if ( dna[ i ] == 'C' ):
        Cs += 1;
    if ( dna[ i ] == 'G' ):
        Gs += 1;
    if ( dna[ i ] == 'T' ):
        Ts += 1;

print "%d %d %d %d" % ( As, Cs, Gs, Ts)
