#!/usr/bin/python
# 
# 
# 
# 
# Kim Brugger (05 Nov 2015), contact: kim@brugger.dk

import sys
import pprint
pp = pprint.PrettyPrinter(indent=4)
import re


dna = "GATGGAACTTGACTACGTAAATT";

dna = "GCTGGCAAACAGATAACAAGCTAATTGTGTCCCTACAAGACATTTGTTAGGCCTTTCAGCGACGAGAGGGCTACAACAAAATTGTAAATACTACGGGCAATCCTGGCGCTTAACCTTGTGCCGCGGCTTCAGGTCCACGGATTGCACCAAGATCCGGGCTAATGATAGAAATAGGGAACGTTAGAGCTGGCGAATGGCAGTGTGTACGATGGAGGTCTGGCTACGCCGTGACACAGTCAATGGGCGTAGACGCAGCCAGATAGCATCCCTAACACCGCCGCGGGACCCTTACACAACCCGTCTAAAGAGAGCTCTTAACAATAAGTTGACCTTTTAAATAGACAGCTTCGCGAAGAGTGTTGGACGGATCTGTGAGGTTACCAAAAGGGGATTTTTGACGCGCGACGGAACCGGCCACAGAAACAGTGTATCGTGACAGCGTTGCGAACTTTTAAACTAACCCCCTTTCTTGATATAAGTTTGGGCCTAGGACACGTCTATGGGCAAGCTCTAGGCGTTGGTCAGGTACCAGTAAAGTTTCGACAGGTCGCTCACGCACCTTCCCAGTCTCTCTGGTACCATAAGGCTTGAATCGATTGAACTGACCGTCGTGGGTTTCCGTTTTGTGGTCGAGTCGCTCGGGCTTCAGACAGGAGATCGTGCAGTACTATACTAAAGGTTCACACGCTACTGGCCTCGTTGGGTTGCTAAAGTCACAAAAGGTGGTGGAAAAATTACTAGAAAGTTTAAATTGGCCCTGCATAGCATCACCTCCATCTCAGATACATAAGTCACAGGAGACTAGTCTAAAGTGAAATAGCAAGCTTTCATAATCTATTCCTAGCAGAGCCACGTCTCCTACGGAACAGCATGCCAAGGAGATGAGCGCG"

revbase = { 'A' : 'T', 
            'C' : 'G', 
            'G' : 'C',
            'T' : 'A' }

revdna = [""]*len(dna)

dna_len = len( dna )

for i in range(0, len(dna)):

    revdna[ dna_len - i - 1] = revbase[ dna[ i ] ]




print "".join( revdna )
