#!/usr/bin/python
# 
# 
# 
# 
# Kim Brugger (05 Nov 2015), contact: kim@brugger.dk

import sys
import pprint
pp = pprint.PrettyPrinter(indent=4)

dna = "GATGGAACTTGACTACGTAAATT";

dna = "GGTGGCCTCACCGTGACTGCCTTTGCTCGTAGATTTAAATTCCACGCAGCAGCAACGTGCGACGTATGCCGGCAGAGGTAAGAATAGCCCTGGACCTTAATCCCGTGATGGCTTCTGACCGTTTCGTTAAGTGCGCTGTCCCACCTTTCGCGAGGAGCTGCTCCTGTTTGCGTGTTCATCGGCCTAAACGACGCCTCGTGCCAATAATTAATTCCTTCCTGCCACGACCGTGACTGGTGCGCTTCCCCTGCTACCATACGACGTGCCATTCCCTACCGTCTGGGGCCGCAATAAGCGAAAGGAAAGCCCATCGTTCTCCGGGTGGAGACGTCGTACTTGTGCGGAATTGTAGCATGTATGCGCAGACACTGAGTGGGATTAGTGGTACATACACTCTGCAGCGGATCACGTTATAAGCTACGGTAGGAAGGGAGCGCCCACCCCAGTGAGTCTGAAGTAAAGACCGGCTATTCCCGCATCTTTATATAACATGAAGTTTGGTCTGCGGAGCGTAAGGTTCCCATGATGAATGATAGCCAGTGGCCCCTTCTCTTGAGTAACCCGTTACCATTCCTCCGACAGGAAAAGGTAAAGCACCATTTGTTACGACCCTGAACTTTACTCATTATATGGAGCGATCCTTCATCGCGCAACTGCAGTACTGGAACCAGGACTTTGGTGAACCTAGGGATTGGTTTGCTGACTTGCAAGGGCTTTCTATTCCATGGCCGCGGGACGTACAGCAGTTCGTCTCCAGCCATACAAGTAATGGCTTATACGCCACCATCTTGAATCGTACCAAGCCTGTTCTTATTAGGTATCGACACAGACTCGCGACCCGTATCACTTCCACATGATAGTTCTCCTTCGCGCGACTTCGGTGGTGGAGTATTATGAACGCAGAGAAGTATAAACTCACTCCATTCTAACGG"

rna = ""

for i in range(0, len(dna)):

    if ( dna[ i ] == 'T' ):
        rna += "U"
    else:
        rna += dna[ i ]


print rna
