#!/usr/bin/python 
# 
# 
# 
# 
# Kim Brugger (05 Nov 2015), contact: kbr@brugger.dk

import sys
import os
import pprint
pp = pprint.PrettyPrinter(indent=4)

#dna   = "GATATATGCATATACTTATAT"
#motif = "ATAT"


dna = "TCGTTATTCTCGTTATTATCTCGTTATTCCCCGTTATTGAGTACCGTTATTGCGTTATTTGGAGACGTTATTCAGCGGCGTTATTGCTGGACAGCGTTATTGCTCGTTATTGTAGTCGCGTTATTATCTCGTTATTCGTTATTCGTTATTAAAAGAATATAGCCACCGTTATTCGTTATTTAGCTAAAAGCGTTATTATGATCGTTATTCGTCGTTATTGCCGAGCGTTATTGCGTTATTTGCGTTATTCTCGACGTTATTACGTTATTGCGTTATTGCGTTATTCGTTATTAACGTTATTTACGTTATTCACGTTATTCGTTATTATCAGACGTTATTGGCATGTCGTTATTTCATTGGCCGTTATTCGTTATTCGTTATTACGTTATTGGACGTTATTACCGTTATTCGTTATTACTGCCACCGTTATTGAAGTTGATCGTTATTCGTTATTTCGTTATTATTGCGTTATTAACGTTATTTACGTTATTACTTCCGATGCGTTATTGGATACTCGTTATTCCTCCCGTTATTTCCGTTATTCGTTATTTTCGAATACCGTTATTCGTTATTGATACGTTATTTAGAAATGGATTGCGTTATTCGTTATTGAGACGTTATTGCGTTATTCGTTATTCGTTATTCCGTTATTTTCGTTATTTCGTTATTATTAAATCGTTATTCGTTATTAACTTAGCGTTATTCGTTATTTCGTTATTCAGTCGTTATTCGTTATTCGTTATTCGTTATTCAGAACTTCACGCGTTATTTAGCCGCACGTTATTCACGTTATTTCGTTATTCGTTATTGGTAACGTACGTTATTTTCTGCGTTATTTGCGTTATTCGACGACGTTATTTCTCGTTATTTAATCGTTATT"

motif = "CGTTATTCG"

res = []

for i in range(0, len(dna) - len(motif) + 1):

    hit = 1
    for j in range(0, len(motif)):
        if ( dna[ i + j ] != motif[ j ]):
            hit = 0
            break

    if ( hit ):
        res.append( i + 1 )

print " ".join(map(str, res))
